version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: libreria
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5555 -b '0.0.0.0'"
    volumes:
      - .:/libreria
    ports:
      - "5555:5555"
    depends_on:
      - db