version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./server/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: libreria
  server:
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5555 -b '0.0.0.0'"
    volumes:
      - ./server:/libreria/server
      - gem_data:/usr/local/bundle
    ports:
      - "5555:5555"
    depends_on:
      - db
  web:
    build: ./client
    tty: true
    volumes:
      - ./client:/libreria/client
    ports:
      - "2525:2525"
volumes:
  gem_data:
